server:
  port: ${PORT:10000}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-damllaajnfac73b54s80-a:5432/devops_db_2bjg}
    username: ${SPRING_DATASOURCE_USERNAME:devops_user}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false