spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS
  cache:
    type: none
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    url: jdbc:postgresql://localhost:5432/devops_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

info:
  app:
    artifact: "@project.artifactId@"
    version: "@project.version@"
    build: "@maven.build.timestamp@"

logging:
  level:
    root: WARN
    es.upm.miw: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true